export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{width:"100%", height:"100%"}}>
      <body style={{width:"100%", height:"100%", margin:0, padding:0}}>{children}</body>
    </html>
  )
}
