FROM python:3.9

WORKDIR /code

ENV PYTHONPATH=/code/tests_environment

COPY ./requirements.txt /code/requirements.txt


RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt


COPY ./tests_environment /code/tests_environment


CMD ["uvicorn", "tests_environment.api.api_endpoints:app", "--host", "0.0.0.0", "--port", "80"]